- name: variables via prompt
  hosts: Local
  connection: local
  vars_prompt:
    - name: USERNAME
      prompt: Type Username 
      private: No

    - name: PASSWORD
      prompt: Type Password
      private: Yes
  tasks:
    - name: Printing variables
      ansible.builtin.debug:
        msg:  "Your Username is {{ USERNAME }} and Password is {{ PASSWORD }}"
